[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["alei <rayingecho@gmail.com>"]
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.8"
regex = "1.10"
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", features = ["thread-pool"] }

[lib]
doctest = false
test = true
